[package]
name = "blockchain-pow-julia"
version = "0.1.0"
edition = "2021"

[dependencies]
enum-as-inner = "0.5.1"
itertools = "0.10.5"
num = "0.4.0"
petgraph = "0.6.3"
rand = "0.8.5"
ring = "0.16.20"
tap = "1.0.1"
thiserror = "1.0.38"
